# Видимый smoke-тест. Скрытая проверка ниже использует банк закрытых тестов и скрыта от клиента.
import sys

ENTRY_POINT = "cat_key_maze"
if globals().get(ENTRY_POINT) is None:
    print(f"Функция или класс {ENTRY_POINT} не найдены", file=sys.stderr)
    sys.exit(1)

print("visible smoke OK")

# ---LEETCOT-HIDDEN-TESTS---
# {"entryPoint":"cat_key_maze","seedGenerator":"import random\n\n\nCASES = [\n    [\"SF\"],\n    [\"S.a\", \"##A\", \"..F\"],\n    [\"SAF\", \"a..\", \"...\"],\n    [\"S#F\", \"...\"],\n    [\"S#F\", \"###\", \"a.A\"],\n    [\"S.a.B\", \"###.#\", \"b...F\"],\n    [\"S..a\", \"##.#\", \"b.BF\"],\n    [\"S.A\", \"...\", \"..F\"],\n    [\"S..aA.F\"],\n    [\"S.b\", \".#B\", \"..F\"],\n]\n\n\ndef generate_case():\n    return (CASES[random.randrange(len(CASES))],)\n","cases":[{"name":"Test 1","seed":1,"expected":4},{"name":"Test 2","seed":2,"expected":1},{"name":"Test 3","seed":3,"expected":4},{"name":"Test 4","seed":4,"expected":4},{"name":"Test 5","seed":5,"expected":4},{"name":"Test 6","seed":6,"expected":4},{"name":"Test 7","seed":7,"expected":6},{"name":"Test 8","seed":8,"expected":4},{"name":"Test 9","seed":9,"expected":4},{"name":"Test 10","seed":10,"expected":4},{"name":"Test 11","seed":11,"expected":4},{"name":"Test 12","seed":12,"expected":4},{"name":"Test 13","seed":13,"expected":-1},{"name":"Test 14","seed":14,"expected":4},{"name":"Test 15","seed":15,"expected":4},{"name":"Test 16","seed":16,"expected":6},{"name":"Test 17","seed":17,"expected":6},{"name":"Test 18","seed":18,"expected":4},{"name":"Test 19","seed":19,"expected":1},{"name":"Test 20","seed":20,"expected":4},{"name":"Test 21","seed":21,"expected":4},{"name":"Test 22","seed":22,"expected":4},{"name":"Test 23","seed":23,"expected":-1},{"name":"Test 24","seed":24,"expected":-1},{"name":"Test 25","seed":25,"expected":-1},{"name":"Test 26","seed":26,"expected":4},{"name":"Test 27","seed":27,"expected":4},{"name":"Test 28","seed":28,"expected":4},{"name":"Test 29","seed":29,"expected":6},{"name":"Test 30","seed":30,"expected":6},{"name":"Test 31","seed":31,"expected":1},{"name":"Test 32","seed":32,"expected":4},{"name":"Test 33","seed":33,"expected":4},{"name":"Test 34","seed":34,"expected":6},{"name":"Test 35","seed":35,"expected":6},{"name":"Test 36","seed":36,"expected":6},{"name":"Test 37","seed":37,"expected":4},{"name":"Test 38","seed":38,"expected":-1},{"name":"Test 39","seed":39,"expected":4},{"name":"Test 40","seed":40,"expected":4}]}
