# Видимый smoke-тест. Скрытая проверка ниже использует банк закрытых тестов и скрыта от клиента.
import sys

ENTRY_POINT = "shortest_energy_path"
if globals().get(ENTRY_POINT) is None:
    print(f'Функция или класс {ENTRY_POINT} не найдены', file=sys.stderr)
    sys.exit(1)

print('visible smoke OK')

# ---LEETCOT-HIDDEN-TESTS---
# {"entryPoint": "shortest_energy_path", "seedGenerator": "import random\n\ndef generate_case():\n    n = random.randint(2, 8)\n    nodes = [chr(ord('A') + i) for i in range(n)]\n    graph = {node: {} for node in nodes}\n    for i in range(n - 1):\n        w = random.randint(1, 9)\n        graph[nodes[i]][nodes[i + 1]] = w\n        graph[nodes[i + 1]][nodes[i]] = w\n    for i in range(n):\n        for j in range(i + 2, n):\n            if random.random() < 0.25:\n                w = random.randint(1, 15)\n                graph[nodes[i]][nodes[j]] = w\n                graph[nodes[j]][nodes[i]] = w\n    if random.random() < 0.15:\n        graph['Z'] = {}\n        return (graph, nodes[0], 'Z')\n    return (graph, random.choice(nodes), random.choice(nodes))\n", "cases": [{"name": "Тест 1", "seed": 1, "expected": 5}, {"name": "Тест 2", "seed": 2, "expected": Infinity}, {"name": "Тест 3", "seed": 3, "expected": 0}, {"name": "Тест 4", "seed": 4, "expected": 0}, {"name": "Тест 5", "seed": 5, "expected": 5}, {"name": "Тест 6", "seed": 6, "expected": 11}, {"name": "Тест 7", "seed": 7, "expected": 10}, {"name": "Тест 8", "seed": 8, "expected": Infinity}, {"name": "Тест 9", "seed": 9, "expected": 8}, {"name": "Тест 10", "seed": 10, "expected": 13}, {"name": "Тест 11", "seed": 11, "expected": Infinity}, {"name": "Тест 12", "seed": 12, "expected": 23}, {"name": "Тест 13", "seed": 13, "expected": 5}, {"name": "Тест 14", "seed": 14, "expected": 0}, {"name": "Тест 15", "seed": 15, "expected": 0}, {"name": "Тест 16", "seed": 16, "expected": 8}, {"name": "Тест 17", "seed": 17, "expected": 11}, {"name": "Тест 18", "seed": 18, "expected": 8}, {"name": "Тест 19", "seed": 19, "expected": 11}, {"name": "Тест 20", "seed": 20, "expected": Infinity}, {"name": "Тест 21", "seed": 21, "expected": 7}, {"name": "Тест 22", "seed": 22, "expected": 5}, {"name": "Тест 23", "seed": 23, "expected": 7}, {"name": "Тест 24", "seed": 24, "expected": Infinity}, {"name": "Тест 25", "seed": 25, "expected": 15}, {"name": "Тест 26", "seed": 26, "expected": 4}, {"name": "Тест 27", "seed": 27, "expected": Infinity}, {"name": "Тест 28", "seed": 28, "expected": 0}, {"name": "Тест 29", "seed": 29, "expected": 5}, {"name": "Тест 30", "seed": 30, "expected": 6}, {"name": "Тест 31", "seed": 31, "expected": Infinity}, {"name": "Тест 32", "seed": 32, "expected": Infinity}, {"name": "Тест 33", "seed": 33, "expected": 11}, {"name": "Тест 34", "seed": 34, "expected": Infinity}, {"name": "Тест 35", "seed": 35, "expected": 9}, {"name": "Тест 36", "seed": 36, "expected": 5}, {"name": "Тест 37", "seed": 37, "expected": 2}, {"name": "Тест 38", "seed": 38, "expected": 8}, {"name": "Тест 39", "seed": 39, "expected": 4}, {"name": "Тест 40", "seed": 40, "expected": Infinity}]}
