# Видимый smoke-тест. Скрытая проверка ниже использует банк закрытых тестов и скрыта от клиента.
import sys

ENTRY_POINT = "cat_repeat"
if globals().get(ENTRY_POINT) is None:
    print(f'Функция или класс {ENTRY_POINT} не найдены', file=sys.stderr)
    sys.exit(1)

print('visible smoke OK')

# ---LEETCOT-HIDDEN-TESTS---
# {"entryPoint": "cat_repeat", "seedGenerator": "import random\nimport string\n\n\ndef generate_case():\n    length = random.randint(1, 5)\n    text = ''.join(random.choices(string.ascii_lowercase, k=length))\n    n = random.randint(0, 10)\n    return (text, n)\n", "cases": [{"name": "Тест 1", "seed": 1, "expected": "ou"}, {"name": "Тест 2", "seed": 2, "expected": "ccccc"}, {"name": "Тест 3", "seed": 3, "expected": "pdpdpdpdpdpdpdpdpd"}, {"name": "Тест 4", "seed": 4, "expected": "hshshshshshshs"}, {"name": "Тест 5", "seed": 5, "expected": "gjrvqgjrvqgjrvqgjrvqgjrvqgjrvqgjrvqgjrvq"}, {"name": "Тест 6", "seed": 6, "expected": "vmgarvmgarvmgarvmgarvmgarvmgarvmgar"}, {"name": "Тест 7", "seed": 7, "expected": "ykbykbykbykbykbykbykbykb"}, {"name": "Тест 8", "seed": 8, "expected": "jjjjjj"}, {"name": "Тест 9", "seed": 9, "expected": "pgerpgerpgerpgerpger"}, {"name": "Тест 10", "seed": 10, "expected": "amammamammamammamamm"}, {"name": "Тест 11", "seed": 11, "expected": "wwulwwulwwulwwulwwulwwulwwulwwulwwul"}, {"name": "Тест 12", "seed": 12, "expected": "gnjjgnjjgnjjgnjjgnjj"}, {"name": "Тест 13", "seed": 13, "expected": "hxuhxu"}, {"name": "Тест 14", "seed": 14, "expected": "qqqqqqqqqq"}, {"name": "Тест 15", "seed": 15, "expected": "atat"}, {"name": "Тест 16", "seed": 16, "expected": ""}, {"name": "Тест 17", "seed": 17, "expected": "khjeskhjeskhjeskhjeskhjeskhjeskhjeskhjes"}, {"name": "Тест 18", "seed": 18, "expected": "dldldl"}, {"name": "Тест 19", "seed": 19, "expected": "uuuuuuuu"}, {"name": "Тест 20", "seed": 20, "expected": "gq"}, {"name": "Тест 21", "seed": 21, "expected": "kkkkkkkk"}, {"name": "Тест 22", "seed": 22, "expected": "gpgpgpgpgpgpgp"}, {"name": "Тест 23", "seed": 23, "expected": "xcpxcpxcpxcpxcpxcp"}, {"name": "Тест 24", "seed": 24, "expected": "vezfvezfvezfvezfvezfvezfvezfvezfvezfvezf"}, {"name": "Тест 25", "seed": 25, "expected": "tvaytvaytvaytvay"}, {"name": "Тест 26", "seed": 26, "expected": "rlrlrlrlrlrlrlrl"}, {"name": "Тест 27", "seed": 27, "expected": "syfbsyfbsyfbsyfbsyfbsyfbsyfbsyfb"}, {"name": "Тест 28", "seed": 28, "expected": "tttttttt"}, {"name": "Тест 29", "seed": 29, "expected": "bppcybppcybppcybppcybppcybppcy"}, {"name": "Тест 30", "seed": 30, "expected": ""}, {"name": "Тест 31", "seed": 31, "expected": "mmmmmm"}, {"name": "Тест 32", "seed": 32, "expected": "yy"}, {"name": "Тест 33", "seed": 33, "expected": "egvmwegvmwegvmwegvmwegvmwegvmwegvmwegvmw"}, {"name": "Тест 34", "seed": 34, "expected": "jafak"}, {"name": "Тест 35", "seed": 35, "expected": "idielidielidielidiel"}, {"name": "Тест 36", "seed": 36, "expected": "baubaubaubau"}, {"name": "Тест 37", "seed": 37, "expected": "cqvvncqvvncqvvncqvvncqvvncqvvncqvvncqvvncqvvncqvvn"}, {"name": "Тест 38", "seed": 38, "expected": "lsbslsbslsbslsbslsbs"}, {"name": "Тест 39", "seed": 39, "expected": "gagaga"}, {"name": "Тест 40", "seed": 40, "expected": "pngrpngrpngrpngrpngrpngrpngrpngrpngrpngr"}]}
