# Видимый smoke-тест. Скрытая проверка ниже использует банк закрытых тестов и скрыта от клиента.
import sys

ENTRY_POINT = "cat_upper"
if globals().get(ENTRY_POINT) is None:
    print(f'Функция или класс {ENTRY_POINT} не найдены', file=sys.stderr)
    sys.exit(1)

print('visible smoke OK')

# ---LEETCOT-HIDDEN-TESTS---
# {"entryPoint": "cat_upper", "seedGenerator": "import random\nimport string\n\n\ndef generate_case():\n    length = random.randint(1, 15)\n    text = ''.join(random.choices(string.ascii_letters + string.digits + \" \", k=length))\n    return (text,)\n", "cases": [{"name": "Тест 1", "seed": 1, "expected": "JYD"}, {"name": "Тест 2", "seed": 2, "expected": "7DF0UQTMMKJBYT"}, {"name": "Тест 3", "seed": 3, "expected": "LI5D"}, {"name": "Тест 4", "seed": 4, "expected": "TTEF"}, {"name": "Тест 5", "seed": 5, "expected": "QWR1PH0WPD"}, {"name": "Тест 6", "seed": 6, "expected": "KFWCJK8UUBEM2"}, {"name": "Тест 7", "seed": 7, "expected": "7YDZFK"}, {"name": "Тест 8", "seed": 8, "expected": "XXMC"}, {"name": "Тест 9", "seed": 9, "expected": "MQLQVDMV"}, {"name": "Тест 10", "seed": 10, "expected": "CEADERZCEE"}, {"name": "Тест 11", "seed": 11, "expected": "21XC1LYD"}, {"name": "Тест 12", "seed": 12, "expected": "QHWY EOC"}, {"name": "Тест 13", "seed": 13, "expected": "S5Y4P"}, {"name": "Тест 14", "seed": 14, "expected": "MV"}, {"name": "Тест 15", "seed": 15, "expected": "AUJ "}, {"name": "Тест 16", "seed": 16, "expected": "DROA1S"}, {"name": "Тест 17", "seed": 17, "expected": "ATXLSIR5P"}, {"name": "Тест 18", "seed": 18, "expected": "HCP"}, {"name": "Тест 19", "seed": 19, "expected": "C4HMVHKLGZ8"}, {"name": "Тест 20", "seed": 20, "expected": "TX3JQ1GU5BZEHDK"}, {"name": "Тест 21", "seed": 21, "expected": "AAR"}, {"name": "Тест 22", "seed": 22, "expected": "IB LHPV4O8UL6R6"}, {"name": "Тест 23", "seed": 23, "expected": "XS0BTXWTQAN4G9F"}, {"name": "Тест 24", "seed": 24, "expected": "YKNKKQS YR6A"}, {"name": "Тест 25", "seed": 25, "expected": "W1A6TD2"}, {"name": "Тест 26", "seed": 26, "expected": "5PBII7EUNKBP"}, {"name": "Тест 27", "seed": 27, "expected": "ERSEQHP0ZPP"}, {"name": "Тест 28", "seed": 28, "expected": "UI"}, {"name": "Тест 29", "seed": 29, "expected": "ELMF6YBC1"}, {"name": "Тест 30", "seed": 30, "expected": "YMN09DXIF"}, {"name": "Тест 31", "seed": 31, "expected": "D"}, {"name": "Тест 32", "seed": 32, "expected": "6J"}, {"name": "Тест 33", "seed": 33, "expected": "KO0E3HH957"}, {"name": "Тест 34", "seed": 34, "expected": "WBOBY8E8V"}, {"name": "Тест 35", "seed": 35, "expected": "VIVJBPDH2"}, {"name": "Тест 36", "seed": 36, "expected": "DBY5RE"}, {"name": "Тест 37", "seed": 37, "expected": "M6PVNC9BX9C"}, {"name": "Тест 38", "seed": 38, "expected": "AVGXDCPLUSN"}, {"name": "Тест 39", "seed": 39, "expected": "QBNT"}, {"name": "Тест 40", "seed": 40, "expected": "KHPPOMWR"}]}
