# Видимый smoke-тест. Скрытая проверка ниже использует банк закрытых тестов и скрыта от клиента.
import sys

ENTRY_POINT = "is_anagram"
if globals().get(ENTRY_POINT) is None:
    print(f'Функция или класс {ENTRY_POINT} не найдены', file=sys.stderr)
    sys.exit(1)

print('visible smoke OK')

# ---LEETCOT-HIDDEN-TESTS---
# {"entryPoint": "is_anagram", "seedGenerator": "import random\n\nletters = 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'\n\n\ndef generate_case():\n    length = random.randint(0, 12)\n    s = ''.join(random.choice(letters) for _ in range(length))\n    if random.random() < 0.5:\n        # A genuine anagram: shuffle the same letters.\n        t = list(s)\n        random.shuffle(t)\n        t = ''.join(t)\n    else:\n        # Not necessarily an anagram — random string, same length distribution.\n        t_length = length if random.random() < 0.7 else random.randint(0, 12)\n        t = ''.join(random.choice(letters) for _ in range(t_length))\n    return (s, t)\n", "cases": [{"name": "Тест 1", "seed": 1, "expected": true}, {"name": "Тест 2", "seed": 2, "expected": true}, {"name": "Тест 3", "seed": 3, "expected": false}, {"name": "Тест 4", "seed": 4, "expected": true}, {"name": "Тест 5", "seed": 5, "expected": true}, {"name": "Тест 6", "seed": 6, "expected": false}, {"name": "Тест 7", "seed": 7, "expected": true}, {"name": "Тест 8", "seed": 8, "expected": true}, {"name": "Тест 9", "seed": 9, "expected": true}, {"name": "Тест 10", "seed": 10, "expected": true}, {"name": "Тест 11", "seed": 11, "expected": false}, {"name": "Тест 12", "seed": 12, "expected": true}, {"name": "Тест 13", "seed": 13, "expected": false}, {"name": "Тест 14", "seed": 14, "expected": true}, {"name": "Тест 15", "seed": 15, "expected": false}, {"name": "Тест 16", "seed": 16, "expected": true}, {"name": "Тест 17", "seed": 17, "expected": true}, {"name": "Тест 18", "seed": 18, "expected": true}, {"name": "Тест 19", "seed": 19, "expected": true}, {"name": "Тест 20", "seed": 20, "expected": true}, {"name": "Тест 21", "seed": 21, "expected": false}, {"name": "Тест 22", "seed": 22, "expected": false}, {"name": "Тест 23", "seed": 23, "expected": true}, {"name": "Тест 24", "seed": 24, "expected": true}, {"name": "Тест 25", "seed": 25, "expected": true}, {"name": "Тест 26", "seed": 26, "expected": false}, {"name": "Тест 27", "seed": 27, "expected": false}, {"name": "Тест 28", "seed": 28, "expected": false}, {"name": "Тест 29", "seed": 29, "expected": true}, {"name": "Тест 30", "seed": 30, "expected": false}, {"name": "Тест 31", "seed": 31, "expected": true}, {"name": "Тест 32", "seed": 32, "expected": true}, {"name": "Тест 33", "seed": 33, "expected": true}, {"name": "Тест 34", "seed": 34, "expected": false}, {"name": "Тест 35", "seed": 35, "expected": false}, {"name": "Тест 36", "seed": 36, "expected": false}, {"name": "Тест 37", "seed": 37, "expected": true}, {"name": "Тест 38", "seed": 38, "expected": true}, {"name": "Тест 39", "seed": 39, "expected": true}, {"name": "Тест 40", "seed": 40, "expected": false}]}
