# Видимый smoke-тест. Скрытая проверка ниже использует банк закрытых тестов и скрыта от клиента.
import sys

ENTRY_POINT = "last_fish"
if globals().get(ENTRY_POINT) is None:
    print(f'Функция или класс {ENTRY_POINT} не найдены', file=sys.stderr)
    sys.exit(1)

print('visible smoke OK')

# ---LEETCOT-HIDDEN-TESTS---
# {"entryPoint": "last_fish", "seedGenerator": "import random\n\n\ndef generate_case():\n    size = random.randint(1, 15)\n    return ([random.randint(-100, 100) for _ in range(size)],)\n", "cases": [{"name": "Тест 1", "seed": 1, "expected": -84}, {"name": "Тест 2", "seed": 2, "expected": 48}, {"name": "Тест 3", "seed": 3, "expected": -6}, {"name": "Тест 4", "seed": 4, "expected": 1}, {"name": "Тест 5", "seed": 5, "expected": 98}, {"name": "Тест 6", "seed": 6, "expected": 88}, {"name": "Тест 7", "seed": 7, "expected": 37}, {"name": "Тест 8", "seed": 8, "expected": -51}, {"name": "Тест 9", "seed": 9, "expected": -14}, {"name": "Тест 10", "seed": 10, "expected": 67}, {"name": "Тест 11", "seed": 11, "expected": -53}, {"name": "Тест 12", "seed": 12, "expected": -98}, {"name": "Тест 13", "seed": 13, "expected": 66}, {"name": "Тест 14", "seed": 14, "expected": 79}, {"name": "Тест 15", "seed": 15, "expected": -91}, {"name": "Тест 16", "seed": 16, "expected": 14}, {"name": "Тест 17", "seed": 17, "expected": 38}, {"name": "Тест 18", "seed": 18, "expected": 14}, {"name": "Тест 19", "seed": 19, "expected": 49}, {"name": "Тест 20", "seed": 20, "expected": -81}, {"name": "Тест 21", "seed": 21, "expected": 7}, {"name": "Тест 22", "seed": 22, "expected": -88}, {"name": "Тест 23", "seed": 23, "expected": 13}, {"name": "Тест 24", "seed": 24, "expected": 93}, {"name": "Тест 25", "seed": 25, "expected": -90}, {"name": "Тест 26", "seed": 26, "expected": -90}, {"name": "Тест 27", "seed": 27, "expected": -36}, {"name": "Тест 28", "seed": 28, "expected": -67}, {"name": "Тест 29", "seed": 29, "expected": 0}, {"name": "Тест 30", "seed": 30, "expected": 1}, {"name": "Тест 31", "seed": 31, "expected": 20}, {"name": "Тест 32", "seed": 32, "expected": -63}, {"name": "Тест 33", "seed": 33, "expected": 66}, {"name": "Тест 34", "seed": 34, "expected": 8}, {"name": "Тест 35", "seed": 35, "expected": -36}, {"name": "Тест 36", "seed": 36, "expected": 28}, {"name": "Тест 37", "seed": 37, "expected": 12}, {"name": "Тест 38", "seed": 38, "expected": -89}, {"name": "Тест 39", "seed": 39, "expected": -51}, {"name": "Тест 40", "seed": 40, "expected": 70}]}
