# Видимый smoke-тест. Скрытая проверка ниже использует банк закрытых тестов и скрыта от клиента.
import sys

ENTRY_POINT = "top_snacks"
if globals().get(ENTRY_POINT) is None:
    print(f'Функция или класс {ENTRY_POINT} не найдены', file=sys.stderr)
    sys.exit(1)

print('visible smoke OK')

# ---LEETCOT-HIDDEN-TESTS---
# {"entryPoint": "top_snacks", "seedGenerator": "import random\n\n\ndef generate_case():\n    names = ['fish', 'milk', 'tea', 'shrimp', 'tuna', 'cream']\n    size = random.randint(0, 70)\n    snacks = [random.choice(names) for _ in range(size)]\n    k = random.randint(0, len(names))\n    return (snacks, k)\n", "cases": [{"name": "Тест 1", "seed": 1, "expected": ["shrimp", "fish", "tuna", "cream", "milk"]}, {"name": "Тест 2", "seed": 2, "expected": ["cream", "fish"]}, {"name": "Тест 3", "seed": 3, "expected": []}, {"name": "Тест 4", "seed": 4, "expected": ["tea", "fish", "milk", "shrimp", "tuna"]}, {"name": "Тест 5", "seed": 5, "expected": ["milk", "cream", "fish", "shrimp"]}, {"name": "Тест 6", "seed": 6, "expected": ["cream", "fish"]}, {"name": "Тест 7", "seed": 7, "expected": []}, {"name": "Тест 8", "seed": 8, "expected": ["shrimp", "milk", "fish"]}, {"name": "Тест 9", "seed": 9, "expected": ["fish"]}, {"name": "Тест 10", "seed": 10, "expected": ["shrimp"]}, {"name": "Тест 11", "seed": 11, "expected": ["tuna", "shrimp", "fish", "cream", "milk", "tea"]}, {"name": "Тест 12", "seed": 12, "expected": ["tuna", "fish", "cream", "milk"]}, {"name": "Тест 13", "seed": 13, "expected": ["milk", "cream"]}, {"name": "Тест 14", "seed": 14, "expected": ["cream", "tea"]}, {"name": "Тест 15", "seed": 15, "expected": ["tea"]}, {"name": "Тест 16", "seed": 16, "expected": ["tea", "cream", "shrimp"]}, {"name": "Тест 17", "seed": 17, "expected": []}, {"name": "Тест 18", "seed": 18, "expected": ["milk"]}, {"name": "Тест 19", "seed": 19, "expected": ["tuna", "fish"]}, {"name": "Тест 20", "seed": 20, "expected": ["shrimp"]}, {"name": "Тест 21", "seed": 21, "expected": ["milk"]}, {"name": "Тест 22", "seed": 22, "expected": ["fish", "milk", "cream", "tea"]}, {"name": "Тест 23", "seed": 23, "expected": ["fish"]}, {"name": "Тест 24", "seed": 24, "expected": []}, {"name": "Тест 25", "seed": 25, "expected": ["tuna"]}, {"name": "Тест 26", "seed": 26, "expected": ["cream"]}, {"name": "Тест 27", "seed": 27, "expected": ["cream", "fish", "tea"]}, {"name": "Тест 28", "seed": 28, "expected": ["milk", "cream", "shrimp"]}, {"name": "Тест 29", "seed": 29, "expected": ["shrimp", "tuna", "tea"]}, {"name": "Тест 30", "seed": 30, "expected": ["tuna", "fish", "tea", "cream", "milk", "shrimp"]}, {"name": "Тест 31", "seed": 31, "expected": []}, {"name": "Тест 32", "seed": 32, "expected": []}, {"name": "Тест 33", "seed": 33, "expected": ["cream", "tuna", "tea"]}, {"name": "Тест 34", "seed": 34, "expected": ["tea", "tuna", "fish", "milk", "shrimp", "cream"]}, {"name": "Тест 35", "seed": 35, "expected": []}, {"name": "Тест 36", "seed": 36, "expected": []}, {"name": "Тест 37", "seed": 37, "expected": ["cream", "tuna", "fish", "shrimp", "tea"]}, {"name": "Тест 38", "seed": 38, "expected": ["fish", "shrimp"]}, {"name": "Тест 39", "seed": 39, "expected": ["fish", "tea", "cream", "shrimp", "milk", "tuna"]}, {"name": "Тест 40", "seed": 40, "expected": ["milk"]}]}
