# Видимый smoke-тест. Скрытая проверка ниже использует банк закрытых тестов и скрыта от клиента.
import sys

ENTRY_POINT = "two_fish"
if globals().get(ENTRY_POINT) is None:
    print(f'Функция или класс {ENTRY_POINT} не найдены', file=sys.stderr)
    sys.exit(1)

print('visible smoke OK')

# ---LEETCOT-HIDDEN-TESTS---
# {"entryPoint": "two_fish", "seedGenerator": "import random\n\n\ndef _count_pairs_summing_to(weights, target):\n    count = 0\n    for a in range(len(weights)):\n        for b in range(a + 1, len(weights)):\n            if weights[a] + weights[b] == target:\n                count += 1\n    return count\n\n\ndef generate_case():\n    # The prompt guarantees exactly one valid pair — keep regenerating until that\n    # invariant actually holds instead of trusting it by construction.\n    while True:\n        n = random.randint(2, 10)\n        weights = [random.randint(-30, 30) for _ in range(n)]\n        i, j = random.sample(range(n), 2)\n        target = weights[i] + weights[j]\n        if _count_pairs_summing_to(weights, target) == 1:\n            return (weights, target)\n", "cases": [{"name": "Тест 1", "seed": 1, "expected": [0, 1]}, {"name": "Тест 2", "seed": 2, "expected": [0, 1]}, {"name": "Тест 3", "seed": 3, "expected": [3, 4]}, {"name": "Тест 4", "seed": 4, "expected": [0, 1]}, {"name": "Тест 5", "seed": 5, "expected": [4, 5]}, {"name": "Тест 6", "seed": 6, "expected": [0, 2]}, {"name": "Тест 7", "seed": 7, "expected": [0, 4]}, {"name": "Тест 8", "seed": 8, "expected": [0, 4]}, {"name": "Тест 9", "seed": 9, "expected": [7, 8]}, {"name": "Тест 10", "seed": 10, "expected": [0, 1]}, {"name": "Тест 11", "seed": 11, "expected": [0, 1]}, {"name": "Тест 12", "seed": 12, "expected": [4, 7]}, {"name": "Тест 13", "seed": 13, "expected": [0, 1]}, {"name": "Тест 14", "seed": 14, "expected": [0, 2]}, {"name": "Тест 15", "seed": 15, "expected": [0, 1]}, {"name": "Тест 16", "seed": 16, "expected": [3, 5]}, {"name": "Тест 17", "seed": 17, "expected": [1, 4]}, {"name": "Тест 18", "seed": 18, "expected": [1, 4]}, {"name": "Тест 19", "seed": 19, "expected": [0, 1]}, {"name": "Тест 20", "seed": 20, "expected": [0, 1]}, {"name": "Тест 21", "seed": 21, "expected": [1, 4]}, {"name": "Тест 22", "seed": 22, "expected": [1, 2]}, {"name": "Тест 23", "seed": 23, "expected": [3, 5]}, {"name": "Тест 24", "seed": 24, "expected": [1, 5]}, {"name": "Тест 25", "seed": 25, "expected": [4, 5]}, {"name": "Тест 26", "seed": 26, "expected": [0, 1]}, {"name": "Тест 27", "seed": 27, "expected": [4, 5]}, {"name": "Тест 28", "seed": 28, "expected": [0, 2]}, {"name": "Тест 29", "seed": 29, "expected": [0, 1]}, {"name": "Тест 30", "seed": 30, "expected": [0, 1]}, {"name": "Тест 31", "seed": 31, "expected": [0, 1]}, {"name": "Тест 32", "seed": 32, "expected": [0, 1]}, {"name": "Тест 33", "seed": 33, "expected": [1, 2]}, {"name": "Тест 34", "seed": 34, "expected": [0, 6]}, {"name": "Тест 35", "seed": 35, "expected": [1, 9]}, {"name": "Тест 36", "seed": 36, "expected": [0, 6]}, {"name": "Тест 37", "seed": 37, "expected": [0, 2]}, {"name": "Тест 38", "seed": 38, "expected": [2, 3]}, {"name": "Тест 39", "seed": 39, "expected": [0, 3]}, {"name": "Тест 40", "seed": 40, "expected": [2, 3]}], "resultOrderInsensitive": true}
