name: Deploy Production on Push

on:
  push:
    branches:
      - main # Срабатывает при каждом коммите/мерже в ветку main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Копируем .env из сейфа раннера в корень свежескачанного кода
      - name: Copy .env file
        run: cp /home/user1/actions-runner/.env ./.env
        
      # Собираем и поднимаем докер-контейнеры
      - name: Build and start Docker containers
        run: docker compose up -d --build
          
      # Чистим старые образы, чтобы при частых коммитах не забить диск сервера
      - name: Clean up unused Docker images
        run: docker image prune -f
